apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vault-agent.fullname" . }}-secrets
  labels:
    {{- include "vault-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.vaultAgent.pvcSize }}
  {{- with .Values.vaultAgent.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}